// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmult_constant.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMult_constant_CfgInitialize(XMult_constant *InstancePtr, XMult_constant_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMult_constant_Set_constant_V(XMult_constant *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMult_constant_WriteReg(InstancePtr->Axilites_BaseAddress, XMULT_CONSTANT_AXILITES_ADDR_CONSTANT_V_DATA, Data);
}

u32 XMult_constant_Get_constant_V(XMult_constant *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMult_constant_ReadReg(InstancePtr->Axilites_BaseAddress, XMULT_CONSTANT_AXILITES_ADDR_CONSTANT_V_DATA);
    return Data;
}

