: ==============================================================
: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
: Version: 2016.1
: Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
: 
: ==============================================================

vivado  -notrace -mode batch -source run_vivado.tcl || exit $?


