:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2016.1
:: Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/SDSoC/2016.1/Vivado_HLS/2016.1/../../Vivado/2016.1/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg484-1 ../Xilinx_hls_mult_constant_1_0.zip
