// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _stream_double_HH_
#define _stream_double_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct stream_double : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > in_data_TDATA;
    sc_in< sc_logic > in_data_TVALID;
    sc_out< sc_logic > in_data_TREADY;
    sc_in< sc_lv<4> > in_data_TKEEP;
    sc_in< sc_lv<4> > in_data_TSTRB;
    sc_in< sc_lv<1> > in_data_TUSER;
    sc_in< sc_lv<1> > in_data_TLAST;
    sc_in< sc_lv<1> > in_data_TID;
    sc_in< sc_lv<1> > in_data_TDEST;
    sc_out< sc_lv<32> > out_data_TDATA;
    sc_out< sc_logic > out_data_TVALID;
    sc_in< sc_logic > out_data_TREADY;
    sc_out< sc_lv<4> > out_data_TKEEP;
    sc_out< sc_lv<4> > out_data_TSTRB;
    sc_out< sc_lv<1> > out_data_TUSER;
    sc_out< sc_lv<1> > out_data_TLAST;
    sc_out< sc_lv<1> > out_data_TID;
    sc_out< sc_lv<1> > out_data_TDEST;


    // Module declarations
    stream_double(sc_module_name name);
    SC_HAS_PROCESS(stream_double);

    ~stream_double();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > in_data_TDATA_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_36;
    sc_signal< sc_logic > out_data_TDATA_blk_n;
    sc_signal< sc_logic > ap_sig_ioackin_out_data_TREADY;
    sc_signal< sc_logic > ap_reg_ioackin_out_data_TREADY;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_36();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_ioackin_out_data_TREADY();
    void thread_in_data_TDATA_blk_n();
    void thread_in_data_TREADY();
    void thread_out_data_TDATA();
    void thread_out_data_TDATA_blk_n();
    void thread_out_data_TDEST();
    void thread_out_data_TID();
    void thread_out_data_TKEEP();
    void thread_out_data_TLAST();
    void thread_out_data_TSTRB();
    void thread_out_data_TUSER();
    void thread_out_data_TVALID();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
